<a href="https://colab.research.google.com/github/mugilan0606/Weather-Prediction/blob/main/Weather_Prediction_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import np_utils
import numpy as np

In [ ]:
seed = 7
np.random.seed(seed)

In [ ]:
data = np.loadtxt("/W_data.txt")

In [ ]:
X_train = data[:4646,:12]
Y_train = data[:4646,12:13]
X_test = data[4646:6936,:12]
Y_test = data[4646:6936,12:13]

In [ ]:
len_y_train = len(Y_train)
len_y_test = len(Y_test)
print(len(Y_train))
print(len(Y_test))

4646
2289


In [ ]:
for i in range(0,len_y_train):
    if(Y_train[i]==1000):
        Y_train[i] = 3
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==100):
        Y_train[i] = 2
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==10):
        Y_train[i] = 1
        Y_train[i] = int(Y_train[i])
    elif(Y_train[i]==1):
        Y_train[i] = 0
        Y_train[i] = int(Y_train[i])

In [ ]:
for i in range(0,len_y_test):
    if(Y_test[i]==1000):
        Y_test[i] = 3
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==100):
        Y_test[i] = 2
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==10):
        Y_test[i] = 1
        Y_test[i] = int(Y_test[i])
    elif(Y_test[i]==1):
        Y_test[i] = 0
        Y_test[i] = int(Y_test[i])

In [ ]:
print(Y_train)
print(Y_test)

[[2.]
 [2.]
 [2.]
 ...
 [3.]
 [3.]
 [3.]]
[[3.]
 [3.]
 [3.]
 ...
 [2.]
 [2.]
 [2.]]


In [ ]:
Y_train = Y_train.astype('int32')
Y_train = np_utils.to_categorical(Y_train,4)
print(Y_train)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [ ]:
Y_test = Y_test.astype('int32')
Y_test = np_utils.to_categorical(Y_test,4)

In [ ]:
model = Sequential()
model.add(Dense(100, input_dim=12, kernel_initializer='uniform', activation='relu'))
model.add(Dense(80, kernel_initializer='uniform', activation='relu'))
model.add(Dense(60, kernel_initializer='uniform', activation='relu'))
model.add(Dense(60, kernel_initializer='uniform', activation='relu'))
model.add(Dense(4))
model.add(Activation('softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               1300      
                                                                 
 dense_1 (Dense)             (None, 80)                8080      
                                                                 
 dense_2 (Dense)             (None, 60)                4860      
                                                                 
 dense_3 (Dense)             (None, 60)                3660      
                                                                 
 dense_4 (Dense)             (None, 4)                 244       
                                                                 
 activation (Activation)     (None, 4)                 0         
                                                                 
Total params: 18,144
Trainable params: 18,144
Non-traina

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=50, batch_size=10, verbose=2, validation_data=(X_test,Y_test))
scores = model.evaluate(X_test, Y_test, verbose=0)

Epoch 1/50
465/465 - 2s - loss: 0.4118 - accuracy: 0.6412 - val_loss: 0.3523 - val_accuracy: 0.6924 - 2s/epoch - 5ms/step
Epoch 2/50
465/465 - 1s - loss: 0.3271 - accuracy: 0.7251 - val_loss: 0.3430 - val_accuracy: 0.6959 - 1s/epoch - 3ms/step
Epoch 3/50
465/465 - 1s - loss: 0.3065 - accuracy: 0.7316 - val_loss: 0.3341 - val_accuracy: 0.6933 - 1s/epoch - 3ms/step
Epoch 4/50
465/465 - 1s - loss: 0.3009 - accuracy: 0.7376 - val_loss: 0.3239 - val_accuracy: 0.7104 - 1s/epoch - 3ms/step
Epoch 5/50
465/465 - 1s - loss: 0.2960 - accuracy: 0.7462 - val_loss: 0.3292 - val_accuracy: 0.6951 - 1s/epoch - 3ms/step
Epoch 6/50
465/465 - 1s - loss: 0.2930 - accuracy: 0.7484 - val_loss: 0.3396 - val_accuracy: 0.6872 - 1s/epoch - 2ms/step
Epoch 7/50
465/465 - 1s - loss: 0.2892 - accuracy: 0.7520 - val_loss: 0.3370 - val_accuracy: 0.7047 - 1s/epoch - 3ms/step
Epoch 8/50
465/465 - 1s - loss: 0.2910 - accuracy: 0.7462 - val_loss: 0.3108 - val_accuracy: 0.7195 - 1s/epoch - 3ms/step
Epoch 9/50
465/465 - 1s 

In [ ]:
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

accuracy: 71.82%


In [ ]:
json_string = model.to_json()
open('Project_model_architecture.json', 'w').write(json_string)
model.save_weights('Project_model_weights.h5',overwrite=True)